[1.14.5]
Title = "Version 1.14.5"
Description = [ "Messed up the previous git merge.",]
GitHubIssues = []

[1.14.4]
Title = "Version 1.14.4"
Description = [ "Apply PackageIt.",]
GitHubIssues = []

[1.14.2]
Title = "Version 1.14.2"
Description = [ "Version 0.0.0", "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
GitHubIssues = []

[0.0.0]
Title = "Version 0.0.0"
Description = [ "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
GitHubIssues = []
